// Mock data for popular apps
export const apps = [
  {
    id: 1,
    name: "WhatsApp",
    icon: "💬",
    color: "bg-green-500",
    followers: "2.3M",
  },
  {
    id: 2,
    name: "Instagram",
    icon: "📷",
    color: "bg-pink-500",
    followers: "1.8M",
  },
  {
    id: 3,
    name: "Facebook",
    icon: "👥",
    color: "bg-blue-600",
    followers: "2.1M",
  },
  {
    id: 4,
    name: "Twitter/X",
    icon: "🐦",
    color: "bg-black",
    followers: "1.5M",
  },
  {
    id: 5,
    name: "TikTok",
    icon: "🎵",
    color: "bg-gray-900",
    followers: "1.9M",
  },
  {
    id: 6,
    name: "Snapchat",
    icon: "👻",
    color: "bg-yellow-400",
    followers: "1.2M",
  },
  {
    id: 7,
    name: "Spotify",
    icon: "🎧",
    color: "bg-green-600",
    followers: "1.4M",
  },
  {
    id: 8,
    name: "YouTube",
    icon: "▶️",
    color: "bg-red-600",
    followers: "2.5M",
  },
];

// Mock feedback data
export const feedbackPosts = [
  {
    id: 1,
    app: "WhatsApp",
    appIcon: "💬",
    type: "like",
    title: "Love the new voice message speed feature!",
    content:
      "Being able to play voice messages at 1.5x or 2x speed is a game changer. Saves so much time with long messages.",
    author: "sarah_tech",
    timestamp: "2h ago",
    upvotes: 234,
    downvotes: 12,
    comments: 45,
    category: "Feature Request",
  },
  {
    id: 2,
    app: "Instagram",
    appIcon: "📷",
    type: "dislike",
    title: "The algorithm is killing small creators",
    content:
      "Reels from big accounts keep flooding my feed while my friends' posts are buried. This is not what Instagram should be about.",
    author: "creator_john",
    timestamp: "4h ago",
    upvotes: 892,
    downvotes: 45,
    comments: 156,
    category: "Algorithm",
  },
  {
    id: 3,
    app: "Facebook",
    appIcon: "👥",
    type: "dislike",
    title: "Too many ads interrupting my feed",
    content:
      "Every 3rd post is an ad now. It's becoming unusable. I understand ads are necessary but this is excessive.",
    author: "mike_user",
    timestamp: "6h ago",
    upvotes: 1203,
    downvotes: 89,
    comments: 234,
    category: "User Experience",
  },
  {
    id: 4,
    app: "Spotify",
    appIcon: "🎧",
    type: "like",
    title: "Discover Weekly is absolutely perfect",
    content:
      "The recommendations just keep getting better. Found so many amazing artists through this playlist.",
    author: "music_lover_99",
    timestamp: "8h ago",
    upvotes: 456,
    downvotes: 23,
    comments: 78,
    category: "Feature Love",
  },
  {
    id: 5,
    app: "Twitter/X",
    appIcon: "🐦",
    type: "dislike",
    title: "Verification system needs to be reworked",
    content:
      "The current verification model is confusing and doesn't actually verify identity anymore.",
    author: "tech_critic",
    timestamp: "12h ago",
    upvotes: 678,
    downvotes: 234,
    comments: 189,
    category: "Policy",
  },
];
